# Generated by Django 6.1.1 on 2026-09-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('year_of_study', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('date_of_admission', models.DateField()),
                ('active_inactivestatus', models.BooleanField(default=True)),
            ],
        ),
    ]
