# Generated by Django 6.1.1 on 2026-09-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_duration', models.CharField(max_length=50)),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trainer_name', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('number_of_seats', models.IntegerField()),
                ('course_active', models.BooleanField(default=True)),
            ],
        ),
    ]
